### ISSUE TITLE
iphone（11.2.6）Connection Failure

### ISSUE THREAD

**Issue by wmysummer** [jellyfin/jellyfin-ios#57] opened 2020-03-19 12:39 UTC
My iPhone 6S (11.2.6) uses the jellyfin for IOS 0.1.1 (5) client to connect to the jellyfin media server, and prompts connection failure when logging in, but Safari can log in normally. My other iPhone 6S plus (11.2.2) can use the jellyfin for IOS 0.1.1 (5) client to log in to the jellyfin media server.
![ios_11 2 6](https://user-images.githubusercontent.com/28956825/77068495-b0268180-6a21-11ea-9eb2-a15135724501.jpg)

Linux Server：Ubuntu Server 18.04.2
Jellyfin Server：10.5.0
Reverse proxy：Nginx/1.14.0（Ubuntu）Enable https

**Comment by thornbill** [comment] 2020-03-29 23:02
Duplicate of #56

**Closed as completed by thornbill** 2020-03-29 23:02 UTC
Labels: duplicate
