### ISSUE TITLE
ios play music will stoped after switch banground

### ISSUE THREAD

**Issue by cangyuegui** [jellyfin/jellyfin-ios#206] opened 2021-01-25 15:20 UTC
ios 
play a music
![7BB1A670-226E-4EB5-A6AC-DE337095CB63](https://user-images.githubusercontent.com/48144788/105725158-93bd7480-5f63-11eb-82d7-190129d6f379.png)

then 
switch to background
![85268F36-9930-4B48-BCEC-F45EDC85D9D6](https://user-images.githubusercontent.com/48144788/105725290-bf405f00-5f63-11eb-82a8-88e4f5395507.png)

it will stoped after about 30sec

**Comment by camc314** [comment] 2021-01-25 16:45
Duplicate of #19 and #153

**Closed as completed** 2021-01-25 17:07 UTC
Labels: duplicate
