### ISSUE TITLE
Blank screen after some time iOS

### ISSUE THREAD

**Issue by karkkijokeri** [jellyfin/jellyfin-ios#414] opened 2023-01-11 23:03 UTC
So basically after some time of watching a movie, the whole app just goes blank white, and the time of the playback stopping doesnt save.

**System (please complete the following information):**
 - iOS Version: 15.6.1 iPad 6th gen
 - Jellyfin Expo version: 39.0.0
 - Jellyfin Server version: 10.8.8

**To Reproduce**

1. Go watch a movie
2. Watch it till like 7mins
3. See error (blank white screen)

**Expected behavior**
Movie resuminf to play, not stopping.

**Screenshots**
Havent captured a one yet

**Additional context**
The player/web frame isnt the only thing going blank, but the whole app, or the player just covers the whole screen. Fixes by restarting but i can reproduce.

**Comment by karkkijokeri** [comment] 2023-01-11 23:04
Update: it onky seems to happen on jellyfin player, native works fine.

**Comment by anthonylavado** [comment] 2023-05-06 17:50
Is this only movies, or does it happen with shows too?

All videos, or only certain ones?

Since you're using an iPad, is this the only app on screen or are you using it in split-screen or similar?

It _sounds_ like #396 in that the page is getting killed for memory reasons, and using the native player kind of gets past that because it's no longer just a webpage but a dedicated activity.

**Comment by karkkijokeri** [comment] 2023-05-06 17:56
Hey!
Movies, gonna test with shows soon.
(gonna test with shows soon)
Only app on screen
My iPad should have enough memory to run a video player, as I don't multitask on it.

**Comment by thornbill** [comment] 2024-11-14 02:11
Closing as a duplicate of #396.

**Closed as not planned by thornbill** 2024-11-14 02:11 UTC
Labels: bug, duplicate
