### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by patchint** [jellyfin/jellyfin-ios#386] opened 2022-08-11 09:31 UTC
**Describe the feature**

Like YouTube Music, Crunchyroll, Netflix... Add an offline mode for mobile version on iOS (And Android too), to listen music... watch content... without network by downloading them inside the app like adding content in VLC.

**Comment by thornbill** [comment] 2022-08-14 01:16
Duplicate of #22 and/or #372

**Closed as not planned** 2022-08-14 01:16 UTC
Labels: feature
