### ISSUE TITLE
Navigation bar is misplaced on ipad 

### ISSUE THREAD

**Issue by ayanamists** [jellyfin/jellyfin-ios#405] opened 2022-11-28 04:50 UTC
**Describe the bug**

On my ipad, navigation bar is in the right place when enter Jellyfin Expo app at first:

![image](https://user-images.githubusercontent.com/44194981/204195716-517aea71-7df4-4991-9444-c382f1d089f7.png)

However, after playing a video in full screen mode and exit, navigation bar is overlapping with the ios status bar:

![image](https://user-images.githubusercontent.com/44194981/204195869-7180ff8f-934e-4226-91e9-a610f39990cb.png)

**System (please complete the following information):**
 - iOS Version: ipadOS 16.1.1 (20B101)
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: 10.8.7

**To Reproduce**

1. Go to Jellyfin Expo app 
2. play any video, jellyfin will play it in full screen mode
3. Tap exit on the upper left corner
4. navigation bar is now overlapping with ios status bar

**Expected behavior**
Navigation bar will not overlapping with ios status bar and be placed in the right position

**Comment by thornbill** [comment] 2022-11-29 05:00
Duplicate of #192

**Closed as not planned** 2022-11-29 05:00 UTC
Labels: bug, duplicate
