### ISSUE TITLE
Transcode on Cellular Data

### ISSUE THREAD

**Issue by Sakooooo** [jellyfin/jellyfin-ios#474] opened 2024-01-04 19:33 UTC
**Describe the feature**

add a setting to automatically transcode to a set quality when on cellular data and for wifi

**Additional context**

no additional context

**Comment by thornbill** [comment] 2024-11-13 23:33
Duplicate of https://github.com/jellyfin/jellyfin-expo/issues/332

**Closed as not planned** 2024-11-13 23:33 UTC
Labels: duplicate, feature
