### ISSUE TITLE
AVPlayerItem Error Code -1100

### ISSUE THREAD

**Issue by billyinferno** [jellyfin/jellyfin-ios#272] opened 2021-06-05 15:13 UTC
Error when playing the video that transcode (transcode is success as per ffmpeg and jellyfin log), and showed error:

The AVPlayerItem instance has failed with the error code -100 and domain "NSURLErrorDomain".

iOS: 14.42 (Iphone 11 Pro)
Jellyfin 10.7.2
Jellyfin iOS 1.4.0 (5.4.0.1)
Native Player Beta (On)

The issue not persist when Native Player Beta is disabled.

**Comment by RickoDean** [comment] 2021-07-03 01:00
I’m getting the same error as well. I’m testing on iOS 15 beta 2 (iPhone 12 Pro Max) and I too am getting the -1100 error on playback

**Comment by thornbill** [comment] 2021-07-03 03:05
Can you provide the media information for the file you are trying to play? Thanks!

**Comment by RickoDean** [comment] 2021-07-03 04:36
I'm using m3u tuner pulling data from Pluto TV parser.

**Comment by thornbill** [comment] 2021-07-29 18:14
Live TV not working is a known issue with the native player. Closing this as a duplicate of #251.

**Closed as completed by thornbill** 2021-07-29 18:14 UTC
Labels: duplicate
