### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by markdegrootnl** [jellyfin/jellyfin-ios#416] opened 2023-01-15 17:27 UTC
**Describe the feature**
Allow self-signed https certificates in iOS app

**Additional context**

Maybe make it a configurable option and disable it by default. 

See: https://features.jellyfin.org/posts/1195/allow-self-signed-https-certificates-in-ios-app

**Comment by thornbill** [comment] 2023-01-18 03:25
Duplicate of #370

**Closed as not planned** 2023-01-18 03:25 UTC
Labels: feature
