### ISSUE TITLE
Exiting Picture in Picture mode ends playback in Native Player

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-ios#440] opened 2023-08-27 21:06 UTC
**Describe the bug**
Exiting Picture in Picture mode ends playback in Native Player

**System (please complete the following information):**
 - iOS Version: 16.3.1
 - Jellyfin Expo version: Jellyfin Mobile (iOS) 1.5.0 (5.5.0.0) Expo Version: 43.0.0
 - Jellyfin Server version: 10.8.10

**To Reproduce**

1. Enable Native Player in Settings
2. Play a video
3. Enter Picture in Picture Mode 
4. Return from Picture in Picture mode (Button on top right)
5. See Issue

**Expected behavior**
Video returns to fullscreen playback

**Screenshots**
None.

**Additional context**
Behaves as expected with native player disabled.

**Comment by thornbill** [comment] 2023-08-27 22:58
Duplicate of #289

**Closed as not planned** 2023-08-27 22:58 UTC
Labels: bug, duplicate
