### ISSUE TITLE
Double subtitles in iOS version of the app

### ISSUE THREAD

**Issue by FrankP34** [jellyfin/jellyfin-ios#165] opened 2020-10-13 15:20 UTC
I am new to jellyfin and media server clients in general. My videos have embedded cc utf-8 subtitles added by handbrake. Everything works as it should using my LG TV’s DLNA media player and jellyfin works as it should in the Roku version of the app. But the iOS version of jellyfin on my iPad and iPhone show double subtitles and I can’t disable them. Any help is appreciated.

**Comment by thornbill** [comment] 2020-10-15 13:45
Duplicate of #98

**Closed as completed by thornbill** 2020-10-15 13:45 UTC
Labels: duplicate
