### ISSUE TITLE
10.9.1 Music sounds stops in background and phone sleeps even after toggling keep screen awake

### ISSUE THREAD

**Issue by SukhsimranSingh** [jellyfin/jellyfin-ios#487] opened 2024-05-17 13:35 UTC
**Describe the bug**

**System (please complete the following information):**
 - iOS Version:17.4.1
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: 10.9.1

**To Reproduce**

1. Go to music in Jellyfin
2. Tap on a .mp3 or any audio
3. swipe up to the home screen
4. you should see the mini display for the audio in the background in the dynamic island, itll show the file playing but there is no sound

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Bm-TM** [comment] 2024-05-26 13:26
hey, yes i got the same. i was about to say the same

**Comment by vincentroyc** [comment] 2024-07-06 15:36
Same here. Sometimes it does not seem to be connected properly detected by the built in audio player and does not appear in the "settings swipe menu".

**Comment by mindaugasjur** [comment] 2024-10-03 14:20
any progress on this?
same issue on my iOS 18.0, music is not working due to "Keep Screen Awake" toggle not working. 
Screen turns off and music stops.

iOS 18.0
JellyFin Mobile 1.5.0 (5.5.0.0)
Expo Version: 43.0.0

Server: 10.9.11

**Comment by thornbill** [comment] 2024-10-16 03:55
Duplicate of #19

**Closed as not planned** 2024-10-16 03:55 UTC
Labels: bug, duplicate
