### ISSUE TITLE
Navigation bar doesn't take status bar height into account after exiting playback with native video player

### ISSUE THREAD

**Issue by Cyberbeni** [jellyfin/jellyfin-ios#421] opened 2023-03-05 11:50 UTC
**Describe the bug**

**System (please complete the following information):**
 - iOS Version: 16.3.1
 - Jellyfin Expo version: 1.5.0 (5.5.0.0)
 - Jellyfin Server version: 10.8.9

**To Reproduce**

https://user-images.githubusercontent.com/8356175/222958678-763f736b-8791-4a62-9b80-f66c9dc3e632.mp4

**Additional context**
I am using an iPad Air 5
If I turn off native video player, it works correctly.

**Comment by thornbill** [comment] 2023-06-08 22:42
Thanks for reporting! This looks like a duplicate of https://github.com/jellyfin/jellyfin-expo/issues/192.

**Closed as not planned** 2023-06-08 22:42 UTC
Labels: bug
